#!/bin/sh
dir=$(dirname "$0"; echo .); dir=${dir%??}
[ -r "$PWD/dash-rc" ]   && export "ENV=$PWD/dash-rc"
[ -r "$dir/dash-rc" ]   && export "ENV=$dir/dash-rc"
[ -r "$HOME/.dash-rc" ] && export "ENV=$HOME/.dash-rc"
sh=bash
command -v "$sh" > /dev/null || sh=zsh
exec rlwrap -Acnb '(){}[],'\''=&$"#;:|\' "$sh" -c 'exec -a zsh dash'
