#!/bin/sh
dir=$(dirname "$0"; echo .); dir=${dir%??}
[ -r "$PWD/dash-rc" ]   && export "ENV=$PWD/dash-rc"
[ -r "$dir/dash-rc" ]   && export "ENV=$dir/dash-rc"
[ -r "$HOME/.dash-rc" ] && export "ENV=$HOME/.dash-rc"
sh=bash
command -v "$sh" > /dev/null || sh=zsh
cmd='exec -a zsh dash'
[ "$1" = '--no-set-name' ] && cmd=dash
exec rlwrap -NAicnb '(){}[],'\''=&$"#;:|\' "$sh" -c "$cmd"
